version: "3.9"
services:
    site:
        build:
            context: .
            args:
                PORT: "8080"
        deploy:
            restart_policy:
                condition: always
        expose:
            - "8080"
        healthcheck:
            test:
                ["CMD", "timeout", "10s", "curl", "-f", "http://localhost:8080"]
            interval: 1m
            timeout: 10s
            retries: 3
            start_period: 30s
        ports:
            - "${WEB_PORT}:8080"
        privileged: true
        stop_grace_period: 3s
